### PR TITLE
Add tag taxonomy to blog example

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds a tag taxonomy to the blog example. Specifically, it adds a `tags` field to the `Post` type and a `/tags/[tag]` endpoint.

### CODE REVIEW

**Comment by seancdavis** [comment]
@lucperkins How do you feel about splitting this off into a separate example? That way the example can stay focused, and our primary example can stay super simple.

**Comment by lucperkins** [comment]
Works for me! I'll get that cooking pretty soon here.

**Comment by lucperkins** [comment]
@seancdavis I've got this working locally. Were you thinking that I should keep this example under my GitHub org and just have it as a personal project or would you like to it have it under the CL org?

**Comment by seancdavis** [comment]
@lucperkins I'd say keep it under your user for now. But you can then open up a PR in contentlayerdev/website to add the example to the /examples page.

**Pull request closed without merging**
